# Generated by Django 4.1.2 on 2024-02-15 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0033_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 15)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 15)),
        ),
        migrations.AlterField(
            model_name='trialperiod',
            name='interested_in_buying',
            field=models.IntegerField(default=0),
        ),
    ]
