# Generated by Django 4.1.2 on 2024-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0035_fin_anotification_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_cnotification',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_cnotification',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_dnotification',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_dnotification',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
